import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches, matchPrecache } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, NetworkOnly, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// Stratégie NetworkFirst pour les requêtes de navigation HTML (ex: chargement direct de l'URL ou ouverture de la PWA)
// Cela garantit que lorsqu'il y a une connexion Internet, le navigateur va DIRECTEMENT chercher la dernière version de index.html
// sur le serveur (Render), évitant le décalage de cache sans nécessiter de Ctrl+Shift+R !
// En cas d'absence de réseau (hors-ligne), il bascule instantanément sur le index.html mis en cache.
const navigationStrategy = new NetworkFirst({
  cacheName: 'edunova-html-cache',
  networkTimeoutSeconds: 3,
  plugins: [
    new ExpirationPlugin({
      maxEntries: 10,
      maxAgeSeconds: 24 * 60 * 60, // 24 heures
    }),
  ],
});

registerRoute(
  new NavigationRoute(
    async (params) => {
      try {
        return await navigationStrategy.handle(params);
      } catch (err) {
        // Fallback ultime sur le index.html préchargé si la requête échoue totalement (100% offline)
        const precachedHtml = await matchPrecache('/index.html');
        if (precachedHtml) {
          return precachedHtml;
        }
        throw err;
      }
    },
    {
      denylist: [/^\/api\//] // Ne jamais intercepter les requêtes API
    }
  )
);

// Cache Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
      })
    ]
  })
);

registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'gstatic-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
      })
    ]
  })
);

// Cache static assets (images, styles, scripts) that might not be precached
registerRoute(
  ({ request }) => ['image', 'style', 'script', 'font'].includes(request.destination),
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 150,
        maxAgeSeconds: 30 * 24 * 60 * 60 // 30 Days
      })
    ]
  })
);

// Never cache Supabase Auth endpoints or session RPCs
registerRoute(
  ({ url }) => url.origin.includes('supabase.co') && (url.pathname.includes('/auth/v1/') || url.pathname.includes('invalidate_user_sessions')),
  new NetworkOnly()
);

// Cache Supabase REST GET requests (profiles, school data, etc.) 
// BUT explicitly exclude Auth and Session endpoints from being cached
registerRoute(
  ({ url, request }) => 
    url.origin.includes('supabase.co') && 
    request.method === 'GET' && 
    !url.pathname.includes('/auth/v1/') &&
    !url.pathname.includes('invalidate_user_sessions'),
  new StaleWhileRevalidate({
    cacheName: 'supabase-get-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 7 * 24 * 60 * 60 // 7 Days
      })
    ]
  })
);

// Background Sync for failed Supabase requests
const bgSyncPlugin = new BackgroundSyncPlugin('edunova-offline-queue', {
  maxRetentionTime: 24 * 60 // 24 hours
});

registerRoute(
  /^https:\/\/.*\.supabase\.co\/rest\/v1\/.*/i,
  new NetworkOnly({
    plugins: [bgSyncPlugin]
  }),
  'POST'
);

registerRoute(
  /^https:\/\/.*\.supabase\.co\/rest\/v1\/.*/i,
  new NetworkOnly({
    plugins: [bgSyncPlugin]
  }),
  'PATCH'
);

registerRoute(
  /^https:\/\/.*\.supabase\.co\/rest\/v1\/.*/i,
  new NetworkOnly({
    plugins: [bgSyncPlugin]
  }),
  'DELETE'
);

// Message listener for skipWaiting, claimClients, and cache purging
self.addEventListener('message', (event) => {
  if (event.data) {
    if (event.data.type === 'SKIP_WAITING' || event.data === 'SKIP_WAITING') {
      self.skipWaiting();
    }
    if (event.data.type === 'CLAIM_CLIENTS') {
      self.clients.claim();
    }
    if (event.data.type === 'CLEAR_CACHE' || event.data.type === 'PURGE_SESSION_CACHE' || event.data.type === 'FORCE_LOGOUT') {
      event.waitUntil(
        caches.keys().then((cacheNames) => {
          return Promise.all(
            cacheNames
              .filter((name) => name.includes('supabase') || name.includes('session') || name.includes('user'))
              .map((name) => caches.delete(name))
          );
        })
      );
    }
  }
});

self.addEventListener('push', (event) => {
  let payload = { title: 'Notification', options: {} };

  if (event.data) {
    try {
      payload = event.data.json();
    } catch (e) {
      payload = { title: event.data.text(), options: {} };
    }
  }

  const { title, options } = payload;
  
  if (!options.icon) {
    options.icon = '/pwa-192x192.png';
  }

  event.waitUntil(
    self.registration.showNotification(title, options).then(() => {
      return self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(clients => {
        clients.forEach(client => {
          client.postMessage({ type: 'PUSH_RECEIVED', payload: payload });
        });
      });
    })
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  const url = event.notification.data && event.notification.data.url ? event.notification.data.url : '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(url) && 'focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(url);
      }
    })
  );
});
